export const TOGGLE_USER_REQUEST = 'TOGGLE_USER_REQUEST'
export const RECEIVE_USER = 'RECEIVE_USER'
export const USER_FAILURE = 'USER_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

export const RECEIVE_EXCHANGES = 'RECEIVE_EXCHANGES'

export const TOGGLE_MONEY_REQUEST = 'TOGGLE_MONEY_REQUEST'
export const RECEIVE_MY_MONEY = 'RECEIVE_MY_MONEY'
export const MONEY_FAILURE = 'MONEY_FAILURE'